services:
  demo_cassandra3:
    port :
      -9042:9042
    network :
      -my_network
  demo_hcx4 :
    port :
      -9000:9000
    network :
      -my_network
  networks :
    my_network :
      external :
        name: my_network